name: Update Dagster Cloud Pipelines
on:
  push:
    branches:
      - master

jobs:
  dagster-cloud-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Cache Docker builds
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Run Dagster Cloud CI action
        uses: dagster-io/dagster-cloud-ci-action@main
        with:
          dagit-url: https://hooli.dagster.cloud/datascienceprod
          api-token: ${{ secrets.DAGSTER_AGENT_TOKEN }}
          experimental-git-data: true